class AddDateToPrescriptions < ActiveRecord::Migration[5.0]
  def change
    add_column :prescriptions, :pt01, :string
    add_column :prescriptions, :pt02, :string
    add_column :prescriptions, :pt03, :string
    add_column :prescriptions, :pt04, :string
    add_column :prescriptions, :pt05, :string
    add_column :prescriptions, :pt06, :string
    add_column :prescriptions, :pt07, :string
    add_column :prescriptions, :pt08, :string
    add_column :prescriptions, :pt09, :string
    add_column :prescriptions, :pt10, :string
    add_column :prescriptions, :pt11, :string
    add_column :prescriptions, :pt12, :string
    add_column :prescriptions, :pt13, :string
    add_column :prescriptions, :pt14, :string
    add_column :prescriptions, :pt15, :string
    add_column :prescriptions, :pt16, :string
    add_column :prescriptions, :pt17, :string
    add_column :prescriptions, :pt18, :string
    add_column :prescriptions, :pt19, :string
    add_column :prescriptions, :pt20, :string
    add_column :prescriptions, :pt21, :string
    add_column :prescriptions, :pt22, :string
    add_column :prescriptions, :pt23, :string
    add_column :prescriptions, :pt24, :string
    add_column :prescriptions, :pt25, :string
    add_column :prescriptions, :po01, :integer
    add_column :prescriptions, :po02, :integer
    add_column :prescriptions, :po03, :integer
    add_column :prescriptions, :po04, :integer
    add_column :prescriptions, :po05, :integer
    add_column :prescriptions, :po06, :integer
    add_column :prescriptions, :po07, :integer
    add_column :prescriptions, :po08, :integer
    add_column :prescriptions, :po09, :integer
    add_column :prescriptions, :po10, :integer
    add_column :prescriptions, :po11, :integer
    add_column :prescriptions, :po12, :integer
    add_column :prescriptions, :po13, :integer
    add_column :prescriptions, :po14, :integer
    add_column :prescriptions, :po15, :integer
    add_column :prescriptions, :po16, :integer
    add_column :prescriptions, :po17, :integer
    add_column :prescriptions, :po18, :integer
    add_column :prescriptions, :po19, :integer
    add_column :prescriptions, :po20, :integer
    add_column :prescriptions, :po21, :integer
    add_column :prescriptions, :po22, :integer
    add_column :prescriptions, :po23, :integer
    add_column :prescriptions, :po24, :integer
    add_column :prescriptions, :po25, :integer
  end
end
